### ISSUE TITLE
Polish language pack download problem

### ISSUE THREAD

**Issue by macialek** [filyp/autocorrect#11]
When trying to download polish language pack `spell = Speller(lang='pl')` I get `couldn't download https://siasky.net/AAC52kUAAmfZF_DUZVMQWWO-tJ3g3_3FDEhR2BUXr4oq8Q, trying next url...`.

**Comment by fsondej** [comment]
I just rerun tests and it downloads fine. It looks that you have some connection problem. If you can't fix it, you can manually download https://siasky.net/AAC52kUAAmfZF_DUZVMQWWO-tJ3g3_3FDEhR2BUXr4oq8Q and put it in PATH_TO_REPO/autocorrect/data/

**Comment by fsondej** [comment]
Links to the dictionaries expired. I changed how they are stored and it should work now.
Fixed in 8a7a1cdd365d17c2f1c86fc303056830f10d8c74

**Comment by macialek** [comment]
It works great. Thank you!
