### ISSUE TITLE
cannot import name 'Speller'

### ISSUE THREAD

**Issue by rash150996** [filyp/autocorrect#23]
from autocorrect import Speller

This line is throwing the error as mentioned in the title. Has it been deprecated or is there any workaround?

**Comment by fsondej** [comment]
Hm, this is strange, it should work fine.
What is the output of
```bash
pip freeze | grep autocorrect
```
and of
```python
import autocorrect
dir(autocorrect)
```

Also, what python version are you using?

**Comment by rash150996** [comment]
Hey,
Thanks for replying to the issue.
Actually, I was trying to import and run it on the terminal as a package but suddenly the 'Speller' seem to be an unknown module.

I am using python --version 3.6.9 for now. But I got to make it work.

**Comment by fsondej** [comment]
So it's working fine now?

**Comment by rash150996** [comment]
It is working fine now. Thanks.
