### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by MohamedAAbdallah** [filyp/autocorrect#35]
I tried pip install autocorrect
didn't work so I downloaded the code from Github and ran
pip install autocorrect-master
gave me the same log and problems
I tried all the versions all didn't work
I have no idea what I'm missing

**Comment by fsondej** [comment]
What your error message and system?

**Comment by Mohamednow25** [comment]
> What's your error message and system?

hey Thank you for trying To help, I solved it the problem was with my python itself so I reinstalled it
Windows 10 (Python 3.9)
