### ISSUE TITLE
how to add a new language (for kyrgyz language)

### ISSUE THREAD

**Issue by Adilbek-byte** [filyp/autocorrect#37]
i did everything by the instruction in the description but i could not find a xml file for my language. Please, anybody tell me how to find and add a new language. 
Thanks a lot in advance!

**Comment by filyp** [comment]
Are you sure you downloaded `https://dumps.wikimedia.org/kywiki/latest/kywiki-latest-pages-articles.xml.bz2`?

**Comment by Adilbek-byte** [comment]
i've downloaded but I didn't understand this command bzip2 -d
hiwiki-latest-pages-articles.xml.bz2 I need to type it in the terminal?


вт, 7 сент. 2021 г. в 20:11, Filip Sondej ***@***.***>:

**Comment by filyp** [comment]
yup

**Comment by filyp** [comment]
In bash.
I'm closing, as it's not an issue with this library. There are many tutorials on the Internet, that can help you work with bash.
